### ISSUE TITLE
Router has no Connect implementation

### ISSUE THREAD

**Issue by Jakeplusplus** [bradcypert/ghast#34]
While implementing the requested change in #28, I noticed that there was no implementation of the Connect method.  An implementation for this should be created

https://github.com/bradcypert/ghast/blob/5f506ce21027a45fc6c7f2faca7f92d10cb56d68/pkg/router/router.go#L80-L82

**Comment by jacobkastensmidt** [comment]
I'm working on a fix for this issue right now.
