### ISSUE TITLE
Migrate our templates to use Go's embeds

### ISSUE THREAD

**Issue by bradcypert** [bradcypert/ghast#9]

**Comment by rafaelrubbioli** [comment]
I'd like to work on this one!

**Comment by rafaelrubbioli** [comment]
Could you direct me to what files should be embeded?

**Comment by rafaelrubbioli** [comment]
I opened [a pr](https://github.com/bradcypert/ghast/pull/13) for this!

**Comment by bradcypert** [comment]
Thank you much for your contribution, @rafaelrubbioli ! It's been merged in!
